name: PortProject
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailSettings__SmtpServer=mailpit
      - EmailSettings__SmtpPort=1025
      - EmailSettings__UseSsl=false
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
     - database
     - mailpit
    networks:
     - portnetwork
    restart: on-failure


  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest" # Use a standard image from Docker Hub
    environment:
      MSSQL_SA_PASSWORD: "yourstrongpassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - portnetwork
  
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    volumes:
      - mailpit-data:/data
    restart: unless-stopped
    networks:
    - portnetwork

networks:
   portnetwork:
   
volumes:
   sqlvolume:
   mailpit-data: