name: PortProject
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
     - database
    networks:
     - portnetwork
    restart: on-failure


  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest" # Use a standard image from Docker Hub
    environment:
      MSSQL_SA_PASSWORD: "yourstrongpassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - portnetwork

networks:
   portnetwork:
   
volumes:
   sqlvolume:
   
 